[package]
name = "uniqr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.6"

[dev-dependencies]
assert_cmd = "2.0.12"
tempfile = "3.8.0"



